object MainReadWrite: TMainReadWrite
  Left = 571
  Top = 361
  Width = 631
  Height = 550
  Caption = 'FTsafe Simple PCSC'
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnActivate = FormActivate
  PixelsPerInch = 96
  TextHeight = 14
  object GroupBox2: TGroupBox
    Left = 8
    Top = 0
    Width = 609
    Height = 481
    TabOrder = 4
    object bConnect: TButton
      Left = 416
      Top = 82
      Width = 169
      Height = 33
      Caption = 'SCardConnect'
      Enabled = False
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 0
      OnClick = bConnectClick
    end
    object bStatus: TButton
      Left = 416
      Top = 188
      Width = 169
      Height = 33
      Caption = 'SCardStatus'
      Enabled = False
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 1
      OnClick = bStatusClick
    end
    object bTransmit: TButton
      Left = 416
      Top = 132
      Width = 169
      Height = 33
      Caption = 'SCardTransmit'
      Enabled = False
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 2
      OnClick = bTransmitClick
    end
    object bDisconnect: TButton
      Left = 416
      Top = 340
      Width = 169
      Height = 33
      Caption = 'SCardDisconnect'
      Enabled = False
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 3
      OnClick = bDisconnectClick
    end
    object bRelease: TButton
      Left = 416
      Top = 393
      Width = 169
      Height = 33
      Caption = 'SCardReleaseContext'
      Enabled = False
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Arial'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 4
      OnClick = bReleaseClick
    end
    object gbData: TGroupBox
      Left = 16
      Top = 104
      Width = 385
      Height = 65
      Caption = 'APDU Input'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 5
      object tDataIn: TEdit
        Left = 8
        Top = 24
        Width = 369
        Height = 25
        AutoSize = False
        Font.Charset = ANSI_CHARSET
        Font.Color = clWindowText
        Font.Height = -14
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
        TabOrder = 0
        OnKeyPress = tDataInKeyPress
      end
    end
    object gbOutData: TGroupBox
      Left = 16
      Top = 200
      Width = 385
      Height = 217
      Caption = 'Data Output'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWindowText
      Font.Height = -12
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      TabOrder = 6
    end
  end
  object cbReader: TComboBox
    Left = 32
    Top = 40
    Width = 369
    Height = 22
    ItemHeight = 14
    TabOrder = 0
    OnChange = cbReaderChange
  end
  object mMsg: TRichEdit
    Left = 32
    Top = 224
    Width = 369
    Height = 177
    Font.Charset = GB2312_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    ScrollBars = ssVertical
    TabOrder = 1
  end
  object bReader: TButton
    Left = 424
    Top = 32
    Width = 169
    Height = 33
    Caption = 'SCardListReaders'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 2
    OnClick = bReaderClick
  end
  object bReset: TButton
    Left = 24
    Top = 432
    Width = 169
    Height = 33
    Caption = 'Clear Output Window'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 3
    OnClick = bResetClick
  end
  object btStatus: TStatusBar
    Left = 0
    Top = 489
    Width = 623
    Height = 27
    Panels = <>
  end
  object bStartPolling: TButton
    Left = 424
    Top = 240
    Width = 169
    Height = 33
    Caption = 'StartPolling'
    Enabled = False
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 6
    OnClick = bStartPollingClick
  end
  object bStopPolling: TButton
    Left = 424
    Top = 296
    Width = 169
    Height = 33
    Caption = 'StopPolling'
    Enabled = False
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -12
    Font.Name = 'Arial'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 7
    OnClick = bStopPollingClick
  end
  object PollTimer: TTimer
    Enabled = False
    OnTimer = PollTimerTimer
    Left = 248
    Top = 432
  end
end
